name: Build and Push Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Replace placeholders in Dockerfile
        run: |
          sed -i "s/{{MAINTAINER}}/${{ github.actor }}@users.noreply.github.com/g" Dockerfile
          sed -i "s/{{REPO_URL}}/https://github.com/${{ github.repository }}/g" Dockerfile

      - name: Build and push multi-platform image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64